name: Project linting

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Project linting compliance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --group test

      - name: Run linter
        run: uv run ruff check